# Generated by Django 5.1.3 on 2024-11-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutiondata',
            name='lat',
            field=models.FloatField(default=12.9756843),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollutiondata',
            name='lng',
            field=models.FloatField(default=77.5660749),
            preserve_default=False,
        ),
    ]
